# Generated by Django 5.0.6 on 2026-06-20 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents_juridiques/')),
                ('version', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archive'), ('ERREUR', "Erreur d'indexation")], default='ACTIF', max_length=20)),
                ('uploade_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document juridique',
                'verbose_name_plural': 'documents juridiques',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ChunkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_texte', models.TextField()),
                ('numero_article', models.CharField(blank=True, max_length=50, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('vector_id', models.CharField(help_text='Identifiant du vecteur correspondant dans ChromaDB.', max_length=255, unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='corpus.documentjuridique')),
            ],
            options={
                'verbose_name': 'chunk de document',
                'verbose_name_plural': 'chunks de document',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='chunkdocument',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_index_par_document'),
        ),
    ]
