# Generated by Django 5.0.6 on 2026-07-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentjuridique',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'Indexation en cours'), ('ACTIF', 'Actif'), ('ARCHIVE', 'Archive'), ('ERREUR', "Erreur d'indexation")], default='EN_COURS', max_length=20),
        ),
    ]
